version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    environment:
      - discovery.type=single-node 
      - cluster.name=elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.0.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:

volumes:
  elastic-data:
